---
version: latest
slug: samba
name: Samba share
description: Expose Home Assistant backup and media with SMB/CIFS mount USB in media
url: https://github.com/home-assistant/addons/tree/master/samba
codenotary: notary@home-assistant.io
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
automount: true
moredisks: []
image: homeassistant/{arch}-addon-samba
init: false
map:
  - backup:rw
  - media:rw
options:
  username: homeassistant
  password: null
  workgroup: WORKGROUP
  compatibility_mode: false
  automount: true
  moredisks: []
  veto_files:
    - ._*
    - .DS_Store
    - Thumbs.db
    - icon?
    - .Trashes
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - fe80::/10
    - fc00::/7
schema:
  username: str
  password: password
  workgroup: str
  compatibility_mode: bool
  veto_files:
    - str
  allow_hosts:
    - str
  automount: bool?
  moredisks:
    - str
udev: true
  #usb: true
host_dbus: true
kernel_modules: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_MODULE
full_access: true
devicetree: false
apparmor: true
host_ipc: true
startup: services
